#!/usr/bin/env python
# *-* coding: UTF-8 *-*

coordonate={"stanga": [-1,0], "dreapta":[1,0], "jos":[0,-1], "sus":[0,1]}




def distanta(string, pozitie):
	directie, valoare=string.split()
	directie=directie.lower()
	if directie in coordonate:
		directie=coordonate[directie]
		print valoare
		pozitie[0]=pozitie[0]+directie[0]*int(valoare)
		pozitie[1]=pozitie[1]+directie[1]*int(valoare)
	


def main():
	try:
		fisier = open("Cursor_Date", "r")
		mesaje = fisier.read()
		fisier.close()
	except IOError:
		print("Nu am putut obține coordonatele.")
		return
	pozitie=[0,0]
	for	i in mesaje.splitlines():
		if i:
			distanta(i, pozitie)
			print pozitie
	rezultat = (pozitie[0]**2 + pozitie[1]**2) ** 0.5
	print rezultat

if __name__ == "__main__":
	main()